# Generated by Django 4.2.5 on 2024-02-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_manager_app", "0003_alter_whatsappmessage_sender_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappmessage",
            name="message_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="message_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="timestamp",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="whatsappmessage",
            name="sender_number",
            field=models.CharField(max_length=20),
        ),
    ]
