# Generated by Django 4.2.5 on 2024-02-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_manager_app", "0004_whatsappmessage_message_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutgoingWhatsAppMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_to_number", models.CharField(max_length=20)),
                ("message_text", models.TextField()),
                ("response_data", models.JSONField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
