# Generated by Django 4.2.5 on 2024-02-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_manager_app", "0005_outgoingwhatsappmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsappLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_to_number", models.CharField(default="", max_length=20)),
                ("message_text", models.TextField(blank=True, null=True)),
                ("response_data", models.JSONField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
